name: Slash-OurNet
version: 1.4
abstract: Web Interface for OurNet::BBS
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  OurNet::BBS: 1.64
  Locale::Maketext::Lexicon: 0.32
  HTML::FromANSI: 0
  HTML::FromText: 0
  Template: 0
  Date::Format: 0
  Date::Parse: 0
  Lingua::ZH::Wrap: 0.02
  if: 0.3
  Devel::Hints: 0.02
  PerlIO::via::trap: 0.1
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.32
